# Generated by Django 2.2.3 on 2019-10-10 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20190914_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('pxjg', '培训结构'), ('gx', '高校'), ('gr', '个人')], default='pxjg', max_length=20),
        ),
        migrations.AlterField(
            model_name='citydict',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 10, 10, 54, 8, 446807)),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 10, 10, 54, 8, 446807)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 10, 10, 54, 8, 447807)),
        ),
    ]
