# Generated by Django 2.2.3 on 2019-10-14 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20191013_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citydict',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 14, 14, 48, 59, 988353)),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 14, 14, 48, 59, 988353)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 14, 14, 48, 59, 989353)),
        ),
    ]
